puts "🌱 Seeding spices..."

# Destroy
Queen.destroy_all
Quote.destroy_all

# Create Queens
ru_paul = Queen.create(name: "Ru Paul", season: 0, winner?: false, sun_sign: "Scorpio", image_url: "../images/ru_paul.png", user_added?: false, hometown: "San Diego, CA")
bianca_del_rio = Queen.create(name: "Bianca Del Rio", season: 6, winner?: true, sun_sign: "Cancer", image_url: "../images/bianca_del_rio.png", user_added?: false, hometown: "Gretna, LA")
trixie_mattel = Queen.create(name: "Trixie Mattel", season: 7, winner?: false, sun_sign: "Virgo", image_url: "../images/trixie_mattel.png", user_added?: false, hometown: "Milwaukee, WI")
adore_delano = Queen.create(name: "Adore Delano", season: 6, winner?: false, sun_sign: "Libra", image_url: "../images/adore_delano.png", user_added?: false, hometown: "Azusa, CA")
katya_zamolodchikova = Queen.create(name: "Katya Zamolodchikova", season: 7, winner?: false, sun_sign: "Taurus", image_url: "../images/katya_zamolodchikova.png", user_added?: false, hometown: "Boston, MA")
kim_chi = Queen.create(name: "Kim Chi", season: 8, winner?: false, sun_sign: "Leo", image_url: "../images/kim_chi.png", user_added?: false, hometown: "Chicago, IL")
violet_chachki = Queen.create(name: "Violet Chachki", season: 7, winner?: true, sun_sign: "Gemini", image_url: "../images/violet_chachki.png", user_added?: false, hometown: "Atlanta, GA")
sasha_velour = Queen.create(name: "Sasha Velour", season: 9, winner?: true, sun_sign: "Cancer", image_url: "../images/sasha_velour.png", user_added?: false, hometown: "Berkeley, CA")
alyssa_edwards = Queen.create(name: "Alyssa Edwards", season: 5, winner?: false, sun_sign: "Capricorn", image_url: "../images/alyssa_edwards.png", user_added?: false, hometown: "Mesquite, TX")
plastique_tiara = Queen.create(name: "Plastique Tiara", season: 11, winner?: false, sun_sign: "Aries", image_url: "../images/plastique_tiara.png", user_added?: false, hometown: "Ho Chi Minh City, Vietnam")
alaska = Queen.create(name: "Alaska", season: 5, winner?: false, sun_sign: "Pisces", image_url: "../images/alaska.png", user_added?: false, hometown: "Erie, PA")
aquaria = Queen.create(name: "Aquaria", season: 10, winner?: true, sun_sign: "Aquarius", image_url: "../images/aquaria.png", user_added?: false, hometown: "West Chester, PA")
naomi_smalls = Queen.create(name: "Naomi Smalls", season: 8, winner?: false, sun_sign: "Virgo", image_url: "../images/naomi_smalls.png", user_added?: false, hometown: "Redlands, CA")
valentina = Queen.create(name: "Valentina", season: 9, winner?: false, sun_sign: "Taurus", image_url: "../images/valentina.png", user_added?: false, hometown: "Bell, CA")
manila_luzon = Queen.create(name: "Manila Luzon", season: 3, winner?: false, sun_sign: "Leo", image_url: "../images/manila_luzon.png", user_added?: false, hometown: "Cottage Grove, MN")
vanessa_vanjie_mateo = Queen.create(name: "Vanessa Vanjie Mateo", season: 10, winner?: false, sun_sign: "Libra", image_url: "../images/vanessa_vanjie_mateo.png", user_added?: false, hometown: "Tampa, FL")
shangela = Queen.create(name: "Shangela", season: 2, winner?: false, sun_sign: "Sagittarius", image_url: "../images/shangela.png", user_added?: false, hometown: "Paris, TX")
bob_the_drag_queen = Queen.create(name: "Bob the Drag Queen", season: 8, winner?: true, sun_sign: "Cancer", image_url: "../images/bob_the_drag_queen.png", user_added?: false, hometown: "Columbus, GA")
shea_coulee = Queen.create(name: "Shea Couleé", season: 9, winner?: false, sun_sign: "Aquarius", image_url: "../images/shea_coulee.png", user_added?: false, hometown: "Plainfield, IL")
trinity_the_tuck = Queen.create(name: "Trinity the Tuck", season: 9, winner?: false, sun_sign: "Sagittarius", image_url: "../images/trinity_the_tuck.png", user_added?: false, hometown: "Birmingham, AL")
courtney_act = Queen.create(name: "Courtney Act", season: 6, winner?: false, sun_sign: "Aquarius", image_url: "../images/courtney_act.png", user_added?: false, hometown: "Brisbane, QLD, Australia")
jinkx_monsoon = Queen.create(name: "Jinkx Monsoon", season: 5, winner?: true, sun_sign: "Virgo", image_url: "../images/jinkx_monsoon.png", user_added?: false, hometown: "Portland, OR")
brooke_lynn_hytes = Queen.create(name: "Brooke Lynn Hytes", season: 11, winner?: false, sun_sign: "Pisces", image_url: "../images/brooke_lynn_hytes.png", user_added?: false, hometown: "Toronto, ON, Canada")
miss_fame = Queen.create(name: "Miss Fame", season: 7, winner?: false, sun_sign: "Aries", image_url: "../images/miss_fame.png", user_added?: false, hometown: "Templeton, CA")
sharon_needles = Queen.create(name: "Sharon Needles", season: 4, winner?: true, sun_sign: "Sagittarius", image_url: "../images/sharon_needles.png", user_added?: false, hometown: "Newton, IA")
detox = Queen.create(name: "Detox", season: 5, winner?: false, sun_sign: "Gemini", image_url: "../images/detox.png", user_added?: false, hometown: "Orlando, FL")
miz_cracker = Queen.create(name: "Miz Cracker", season: 10, winner?: false, sun_sign: "Aries", image_url: "../images/miz_cracker.png", user_added?: false, hometown: "Seattle, WA")
gigi_goode = Queen.create(name: "Gigi Goode", season: 12, winner?: false, sun_sign: "Sagittarius", image_url: "../images/gigi_goode.png", user_added?: false, hometown: "Woodstock, IL")
pearl = Queen.create(name: "Pearl", season: 7, winner?: false, sun_sign: "Virgo", image_url: "../images/pearl.png", user_added?: false, hometown: "St. Petersburg, FL")
farrah_moan = Queen.create(name: "Farrah Moan", season: 9, winner?: false, sun_sign: "Virgo", image_url: "../images/farrah_moan.png", user_added?: false, hometown: "Houston, TX")
willam = Queen.create(name: "Willam", season: 4, winner?: false, sun_sign: "Cancer", image_url: "../images/willam.png", user_added?: false, hometown: "Philadelphia, PA")
ben_de_la_creme = Queen.create(name: "BenDeLaCreme", season: 6, winner?: false, sun_sign: "Libra", image_url: "../images/ben_de_la_creme.png", user_added?: false, hometown: "Litchfield, CT")
yvie_oddly = Queen.create(name: "Yvie Oddly", season: 11, winner?: true, sun_sign: "Leo", image_url: "../images/yvie_oddly.png", user_added?: false, hometown: "Denver, CO")
monet_x_change = Queen.create(name: "Monét X Change", season: 10, winner?: false, sun_sign: "Pisces", image_url: "../images/monet_x_change.png", user_added?: false, hometown: "Brooklyn, NY")
latrice_royale = Queen.create(name: "Latrice Royale", season: 4, winner?: false, sun_sign: "Aquarius", image_url: "../images/latrice_royale.png", user_added?: false, hometown: "Compton, CA")
raja = Queen.create(name: "Raja", season: 3, winner?: true, sun_sign: "Gemini", image_url: "../images/raja.png", user_added?: false, hometown: "Baldwin Park, CA")
kameron_michaels = Queen.create(name: "Kameron Michaels", season: 10, winner?: false, sun_sign: "Leo", image_url: "../images/kameron_michaels.png", user_added?: false, hometown: "Nashville, TN")
milk = Queen.create(name: "Milk", season: 6, winner?: false, sun_sign: "Cancer", image_url: "../images/milk.png", user_added?: false, hometown: "Syracuse, NY")
aja = Queen.create(name: "Aja", season: 9, winner?: false, sun_sign: "Capricorn", image_url: "../images/aja.png", user_added?: false, hometown: "Brooklyn, NY")
blair_st_clair = Queen.create(name: "Blair St. Clair", season: 10, winner?: false, sun_sign: "Taurus", image_url: "../images/blair_st_clair.png", user_added?: false, hometown: "Indianapolis, IN")
scarlet_envy = Queen.create(name: "Scarlet Envy", season: 11, winner?: false, sun_sign: "Pisces", image_url: "../images/scarlet_envy.png", user_added?: false, hometown: "Louisville, KY")
jaida_essence_hall = Queen.create(name: "Jaida Essence Hall", season: 12, winner?: true, sun_sign: "Sagittarius", image_url: "../images/jaida_essence_hall.png", user_added?: false, hometown: "Milwaukee, WI")
thorgy_thor = Queen.create(name: "Thorgy Thor", season: 8, winner?: false, sun_sign: "Gemini", image_url: "../images/thorgy_thor.png", user_added?: false, hometown: "Long Island, NY")
nina_west = Queen.create(name: "Nina West", season: 11, winner?: false, sun_sign: "Leo", image_url: "../images/nina_west.png", user_added?: false, hometown: "Greentown, OH")
tatianna = Queen.create(name: "Tatianna", season: 2, winner?: false, sun_sign: "Sagittarius", image_url: "../images/tatianna.png", user_added?: false, hometown: "Arlington, VA")
monique_heart = Queen.create(name: "Monique Heart", season: 10, winner?: false, sun_sign: "Gemini", image_url: "../images/monique_heart.png", user_added?: false, hometown: "Long Island, NY")
heidi_n_closet = Queen.create(name: "Heidi N Closet", season: 12, winner?: false, sun_sign: "Libra", image_url: "../images/heidi_n_closet.png", user_added?: false, hometown: "Ramseur, NC")
chi_chi_devayne = Queen.create(name: "Chi Chi Devayne", season: 8, winner?: false, sun_sign: "Libra", image_url: "../images/chi_chi_devayne.png", user_added?: false, hometown: "Shreveport, LA")
gia_gunn = Queen.create(name: "Gia Gunn", season: 6, winner?: false, sun_sign: "Taurus", image_url: "../images/gia_gunn.png", user_added?: false, hometown: "Carpentersville, IL")
laganja_estranja = Queen.create(name: "Laganja Estranja", season: 6, winner?: false, sun_sign: "Capricorn", image_url: "../images/laganja_estranja.png", user_added?: false, hometown: "Dallas, TX")

# Create Quotes
Quote.create(quote: "She done already done had herses!", claps: 0, queen_id: ru_paul.id, user_added?: false)
Quote.create(quote: "We're all born naked and the rest is drag.", claps: 1, queen_id: ru_paul.id, user_added?: false)
Quote.create(quote: "Sashay away.", claps: 0, queen_id: ru_paul.id, user_added?: false)
Quote.create(quote: "If you can't love yourself, how the hell are you gonna love somebody else? Can I get an amen up in here?", claps: 0, queen_id: ru_paul.id, user_added?: false)
Quote.create(quote: "Extravaganza Eleganza!", claps: 0, queen_id: ru_paul.id, user_added?: false)
Quote.create(quote: "Not today Satan! Not today!", claps: 1, queen_id: bianca_del_rio.id, user_added?: false)
Quote.create(quote: "Don't piss on my leg and tell me it's raining.", claps: 0, queen_id: bianca_del_rio.id, user_added?: false)
Quote.create(quote: "'Wide and Sassy', that was my name in prison.", claps: 0, queen_id: bianca_del_rio.id, user_added?: false)
Quote.create(quote: "She doesn't know how to execute couture, she can't even spell it!", claps: 0, queen_id: bianca_del_rio.id, user_added?: false)
Quote.create(quote: "If I wanted to come for you, I'd come into your room at night and cut your wigs up.", claps: 0, queen_id: bianca_del_rio.id, user_added?: false)
Quote.create(quote: "There's nobody in here, it's like a Morgan McMichaels meet-and-greet.", claps: 0, queen_id: trixie_mattel.id, user_added?: false)
Quote.create(quote: "Poisoning the wig water supply? Big mistake. Huge." , claps: 0, queen_id: trixie_mattel.id, user_added?: false)
Quote.create(quote: " I wouldn't be surprised if we never saw Denise Richards again.", claps: 1, queen_id: trixie_mattel.id, user_added?: false)
Quote.create(quote: "I wish murder was legal.", claps: 1, queen_id: trixie_mattel.id, user_added?: false)
Quote.create(quote: "I'm from Azusa. I'll stab a bitch.", claps: 1, queen_id: adore_delano.id, user_added?: false)
Quote.create(quote: "Bianca is hilarious. She's everything I wanna be when I'm 57.", claps: 0, queen_id: adore_delano.id, user_added?: false)
Quote.create(quote: "I looked like a Lesbian Jonas Brother.", claps: 4, queen_id: adore_delano.id, user_added?: false)
Quote.create(quote: "She looks fucking bomb.com.org.co.uk.", claps: 3, queen_id: adore_delano.id, user_added?: false)
Quote.create(quote: "I wanted to show my hog body.", claps: 0, queen_id: adore_delano.id, user_added?: false)
Quote.create(quote: "Oh my gosh, no, yeah, we're here, we're fucking queer, and we're not going anyweer.", claps: 0, queen_id: adore_delano.id, user_added?: false)
Quote.create(quote: "I am sweating like a hooker in church.", claps: 0, queen_id: katya_zamolodchikova.id, user_added?: false)
Quote.create(quote: "I feel confident, I feel sexy, I feel stupid.", claps: 0, queen_id: katya_zamolodchikova.id, user_added?: false)
Quote.create(quote: "I'm not a dancer, per se, but I can move my body in a compelling way... it usually compels people to leave the room.", claps: 1, queen_id: katya_zamolodchikova.id, user_added?: false)
Quote.create(quote: "H-E-A-R bitch, I am HERE!", claps: 0, queen_id: katya_zamolodchikova.id, user_added?: false)
Quote.create(quote: "If you're not embarrassed about last year you're not making any progress.", claps: 0, queen_id: katya_zamolodchikova.id, user_added?: false)
Quote.create(quote: "I came to DESTROY EVERYONE, with my make-up.", claps: 0, queen_id: kim_chi.id, user_added?: false)
Quote.create(quote: "America is a kitchen that needs a strong chef. Never trust a skinny cook.", claps: 1, queen_id: kim_chi.id, user_added?: false)
Quote.create(quote: "I'm numb from the waist down, tuck included.", claps: 0, queen_id: violet_chachki.id, user_added?: false)
Quote.create(quote: "I'm going to go smoke something...Meth.", claps: 0, queen_id: violet_chachki.id, user_added?: false)
Quote.create(quote: "I love everyone here, you know? But I love myself a lot more." , claps: 1, queen_id: violet_chachki.id, user_added?: false)
Quote.create(quote: "Pain is beauty, and I'm the prettiest.", claps: 0, queen_id: violet_chachki.id, user_added?: false)
Quote.create(quote: "Wearing white after International Day of Labor? If you were my mother's daughter, she would drown you in river!", claps: 0, queen_id: sasha_velour.id, user_added?: false)
Quote.create(quote: "This is 'RuPaul's Best Group Therapy Race'.", claps: 1, queen_id: sasha_velour.id, user_added?: false)
Quote.create(quote: "Don't get bitter, just get better.", claps: 0, queen_id: alyssa_edwards.id, user_added?: false)
Quote.create(quote: "Every woman has a secret. Mine happens to be a little bigger... I'm a man.", claps: 0, queen_id: alyssa_edwards.id, user_added?: false)
Quote.create(quote: "It's not personal, it's drag.", claps: 1, queen_id: alyssa_edwards.id, user_added?: false)
Quote.create(quote: "Wrong queen mama cuz I'm not the one.", claps: 0, queen_id: alyssa_edwards.id, user_added?: false)
Quote.create(quote: "Mama, this is garbage.", claps: 0, queen_id: alyssa_edwards.id, user_added?: false)
Quote.create(quote: "I like to describe my drag as 3 P's: polished, persistent and pussy.", claps: 0, queen_id: plastique_tiara.id, user_added?: false)
Quote.create(quote: "Oh y'all thought I was done! [does a split]", claps: 0, queen_id: plastique_tiara.id, user_added?: false)
Quote.create(quote: "I'm a dancing queen, I'm a look queen, I can perform, I can beat my mug the house down, I can give you a death drop, 1-2-8 count to a split if you want to, so, I'm everything.", claps: 0, queen_id: plastique_tiara.id, user_added?: false)
Quote.create(quote: "I look the best, I smell the best, this is my runway.", claps: 1, queen_id: plastique_tiara.id, user_added?: false)
Quote.create(quote: "Don't worry, if drag doesn't work out, you will always have something to fall back on: your backrolls.", claps: 0, queen_id: alaska.id, user_added?: false)
Quote.create(quote: "Drag fucking hurts.", claps: 0, queen_id: alaska.id, user_added?: false)
Quote.create(quote: "I live for Chaz Bono. Chaz Bono came out of Cher's vagina!" , claps: 0, queen_id: alaska.id, user_added?: false)
Quote.create(quote: "The key to doing well in this challenge is keeping your lip-sync straight, your choreography gay, and your characterization bicurious.", claps: 0, queen_id: aquaria.id, user_added?: false)
Quote.create(quote: "My humor comes from a... very confused place in my brain." , claps: 1, queen_id: aquaria.id, user_added?: false)
Quote.create(quote: "I'm like Gandi.", claps: 0, queen_id: aquaria.id, user_added?: false)
Quote.create(quote: "I'm up in the wigotry of it all!", claps: 0, queen_id: naomi_smalls.id, user_added?: false)
Quote.create(quote: "Do you know how many dresses at Wet Seal I could get with $5,000?", claps: 1, queen_id: naomi_smalls.id, user_added?: false)
Quote.create(quote: "LIFE'S NOT FAIR.", claps: 0, queen_id: naomi_smalls.id, user_added?: false)
Quote.create(quote: "Beauty is pain, and I believe America needs to toughen up.", claps: 0, queen_id: naomi_smalls.id, user_added?: false)
Quote.create(quote: "Escandalo!", claps: 0, queen_id: valentina.id, user_added?: false)
Quote.create(quote: "Trinity Taylor, I once told you you were beautiful inside and out, I lied you ugly stripper!", claps: 0, queen_id: valentina.id, user_added?: false)
Quote.create(quote: "Am I the villain? Villaintina? Me?", claps: 1, queen_id: valentina.id, user_added?: false)
Quote.create(quote: "Boots the house down, mama, yes gawd. *tongue pop*", claps: 0, queen_id: valentina.id, user_added?: false)
Quote.create(quote: "How dare you.", claps: 0, queen_id: valentina.id, user_added?: false)
Quote.create(quote: "Have you ever tried eating your makeup, so you'll be pretty on the inside too?", claps: 0, queen_id: manila_luzon.id, user_added?: false)
Quote.create(quote: "I feel like a strippa!", claps: 1, queen_id: manila_luzon.id, user_added?: false)
Quote.create(quote: "Oh, I'm so glad you covered up your face.", claps: 0, queen_id: manila_luzon.id, user_added?: false)
Quote.create(quote: "Is this bitch for real?!?", claps: 0, queen_id: manila_luzon.id, user_added?: false)
Quote.create(quote: "Get these cookies, baby!", claps: 0, queen_id: vanessa_vanjie_mateo.id, user_added?: false)
Quote.create(quote: "Burn the wigs! Burn those fucking wigs!", claps: 1, queen_id: vanessa_vanjie_mateo.id, user_added?: false)
Quote.create(quote: "I was humilita-humilated...I was embarrassed.", claps: 0, queen_id: vanessa_vanjie_mateo.id, user_added?: false)
Quote.create(quote: "WORK BERTHA!", claps: 0, queen_id: vanessa_vanjie_mateo.id, user_added?: false)
Quote.create(quote: "Soficsta-, sofic-, solicam-, soficmicaleted.", claps: 0, queen_id: vanessa_vanjie_mateo.id, user_added?: false)
Quote.create(quote: "Halleloo!", claps: 0, queen_id: shangela.id, user_added?: false)
Quote.create(quote: "I don't have a sugar daddy. I've never had a sugar daddy. If I wanted a sugar daddy, yes, I could probably go out and get one because I am what? Sickening!", claps: 0, queen_id: shangela.id, user_added?: false)
Quote.create(quote: "I am the Nancy Drew of drag.", claps: 1, queen_id: shangela.id, user_added?: false)
Quote.create(quote: "You'll never be glamour.", claps: 0, queen_id: shangela.id, user_added?: false)
Quote.create(quote: "Here come the dragons!", claps: 0, queen_id: shangela.id, user_added?: false)
Quote.create(quote: "The Gay Agenda. And it's designed by lesbians, so you know it works.", claps: 0, queen_id: shangela.id, user_added?: false)
Quote.create(quote: "If you wanna do like memorable drag next week I can give you some tips.", claps: 1, queen_id: bob_the_drag_queen.id, user_added?: false)
Quote.create(quote: "If my intentions were to hurt you, you'd be crying right now, bitch!", claps: 0, queen_id: bob_the_drag_queen.id, user_added?: false)
Quote.create(quote: "No one better be disrespecting me.", claps: 0, queen_id: bob_the_drag_queen.id, user_added?: false)
Quote.create(quote: "Why y'all gagging, I bring it to you every episode!", claps: 0, queen_id: bob_the_drag_queen.id, user_added?: false)
Quote.create(quote: "Mama, the drama!", claps: 1, queen_id: shea_coulee.id, user_added?: false)
Quote.create(quote: "I might be pretty on the outside, but on the inside I'm pure garbage!", claps: 0, queen_id: shea_coulee.id, user_added?: false)
Quote.create(quote: "Messica Simpson.", claps: 0, queen_id: shea_coulee.id, user_added?: false)
Quote.create(quote: "Chicago drag is the motherfuckingbomb.com... that's right, bitch, it's got its own domain!", claps: 0, queen_id: shea_coulee.id, user_added?: false)
Quote.create(quote: "Nothing reminds me of home more than a big wiener sandwiched in between 2 buns.", claps: 0, queen_id: shea_coulee.id, user_added?: false)
Quote.create(quote: "Mama, you look so good it's damn near sinful.", claps: 0, queen_id: shea_coulee.id, user_added?: false)
Quote.create(quote: "Talk shit, get hit.", claps: 0, queen_id: shea_coulee.id, user_added?: false)
Quote.create(quote: "I love her, but bye bitch!", claps: 0, queen_id: trinity_the_tuck.id, user_added?: false)
Quote.create(quote: "I call shade!", claps: 1, queen_id: trinity_the_tuck.id, user_added?: false)
Quote.create(quote: "I have 50 units of botox in my face. I don't know what y'all want from me.", claps: 0, queen_id: trinity_the_tuck.id, user_added?: false)
Quote.create(quote: "It kinda looks like gay birds shit on her arm.", claps: 0, queen_id: trinity_the_tuck.id, user_added?: false)
Quote.create(quote: "I don't know what the fuck she's saying, but girl, I am living.", claps: 0, queen_id: trinity_the_tuck.id, user_added?: false)
Quote.create(quote: "Money can't buy everything, but sure can buy A LOT of plastic surgery!", claps: 0, queen_id: trinity_the_tuck.id, user_added?: false)
Quote.create(quote: "Well, everyone is resting on ugly, why can't I rely on being pretty?", claps: 1, queen_id: courtney_act.id, user_added?: false)
Quote.create(quote: "I can look like Linda, and walk like Naomi, get messed up like Kate, and you don't even know me. Looking like this is a goddamn stunt. All you other bitches better lick my...foot.", claps: 0, queen_id: courtney_act.id, user_added?: false)
Quote.create(quote: "Delusion - convince yourself!", claps: 1, queen_id: jinkx_monsoon.id, user_added?: false)
Quote.create(quote: "CAN I GET, CAN I GET AN AMEN", claps: 0, queen_id: jinkx_monsoon.id, user_added?: false)
Quote.create(quote: "I am Seattle's premier Jewish narcoleptic drag queen!", claps: 0, queen_id: jinkx_monsoon.id, user_added?: false)
Quote.create(quote: "When you're dealing with people judging what you do, you just have to let it roll off like water off a duck's back.", claps: 0, queen_id: jinkx_monsoon.id, user_added?: false)
Quote.create(quote: "You're so full of shit the toilet's jealous.", claps: 0, queen_id: jinkx_monsoon.id, user_added?: false)
Quote.create(quote: "I tried to tease it but I just pissed it off.", claps: 0, queen_id: jinkx_monsoon.id, user_added?: false)
Quote.create(quote: "Rodger. You're like the sis- You're like the mo- You're like the grandmother I never had." , claps: 0, queen_id: jinkx_monsoon.id, user_added?: false)
Quote.create(quote: "Death drops terrify me.", claps: 1, queen_id: brooke_lynn_hytes.id, user_added?: false)
Quote.create(quote: "This is my lady garden and I am not ashamed!", claps: 0, queen_id: brooke_lynn_hytes.id, user_added?: false)
Quote.create(quote: "Mama's homo.", claps: 0, queen_id: brooke_lynn_hytes.id, user_added?: false)
Quote.create(quote: "I need to relax! MY ENERGY IS VERY TENSE RIGHT NOW!", claps: 0, queen_id: brooke_lynn_hytes.id, user_added?: false)
Quote.create(quote: "It's not like I don't get it, I'm pretty and people hate me.", claps: 0, queen_id: miss_fame.id, user_added?: false)
Quote.create(quote: "Nobody wants to pop the corn and feed the children. That's disgusting. Let me pop this bunion and have the kids feasting for days?", claps: 0, queen_id: miss_fame.id, user_added?: false)
Quote.create(quote: "Why did you bring that TRAMP back?", claps: 0, queen_id: miss_fame.id, user_added?: false)
Quote.create(quote: "I wish I could cry but, goddamn botox got me every time! Other than that, I'd like to thank Mexico for the tapeworm that snatched my body, and the man upstairs.", claps: 1, queen_id: miss_fame.id, user_added?: false)
Quote.create(quote: "She ordered those tears from China.", claps: 0, queen_id: sharon_needles.id, user_added?: false)
Quote.create(quote: "3 words to describe Sharon Needles are: beautiful, spooky and stupid.", claps: 0, queen_id: sharon_needles.id, user_added?: false)
Quote.create(quote: "When in doubt, freak 'em out.", claps: 1, queen_id: sharon_needles.id, user_added?: false)
Quote.create(quote: "I like spotlight, not sunlight.", claps: 0, queen_id: sharon_needles.id, user_added?: false)
Quote.create(quote: "There's nothing natural about me.", claps: 0, queen_id: sharon_needles.id, user_added?: false)
Quote.create(quote: "Being booed off stage is just an applause from ghosts.", claps: 0, queen_id: sharon_needles.id, user_added?: false)
Quote.create(quote: "Send me to hell, I don't look good in white.", claps: 0, queen_id: sharon_needles.id, user_added?: false)
Quote.create(quote: "Ugh?!", claps: 0, queen_id: detox.id, user_added?: false)
Quote.create(quote: "Alaska, I don’t know what I've gotten from you besides chlamydia.", claps: 1, queen_id: detox.id, user_added?: false)
Quote.create(quote: "Take life less seriously and have fun and tuck your dick properly.", claps: 0, queen_id: detox.id, user_added?: false)
Quote.create(quote: "RO-LASKA-TOX: It's the new prescription drug for people who are gagging.", claps: 0, queen_id: detox.id, user_added?: false)
Quote.create(quote: "I just don’t give 2 shits.", claps: 0, queen_id: detox.id, user_added?: false)
Quote.create(quote: "For what?", claps: 0, queen_id: detox.id, user_added?: false)
Quote.create(quote: "And I'm disgusting.", claps: 0, queen_id: miz_cracker.id, user_added?: false)
Quote.create(quote: "If it's thin, white and salty. It’s probably a cracker.", claps: 1, queen_id: miz_cracker.id, user_added?: false)
Quote.create(quote: "Come for the face, stay for the crazy.", claps: 0, queen_id: miz_cracker.id, user_added?: false)
Quote.create(quote: "I live in Harlem, so people call me by name all the time.", claps: 0, queen_id: miz_cracker.id, user_added?: false)
Quote.create(quote: "She opened the oatmeal container, pulled out all of the oats individually and felt them all.", claps: 0, queen_id: miz_cracker.id, user_added?: false)
Quote.create(quote: "Drag... IS a contact sport.", claps: 0, queen_id: miz_cracker.id, user_added?: false)
Quote.create(quote: "It's Easter Sunday in the trailer park, I just joined a lesbian biker gang.", claps: 1, queen_id: gigi_goode.id, user_added?: false)
Quote.create(quote: "Can I just say that I wanna eat your hair right now?" , claps: 0, queen_id: gigi_goode.id, user_added?: false)
Quote.create(quote: "I understand your concern, but I do not have the same concern.", claps: 0, queen_id: gigi_goode.id, user_added?: false)
Quote.create(quote: "Good morning sinners.", claps: 0, queen_id: gigi_goode.id, user_added?: false)
Quote.create(quote: "Crystal's singing voice is almost Kermit, but like, if Kermit smoked a lot of pot.", claps: 0, queen_id: gigi_goode.id, user_added?: false)
Quote.create(quote: "Thank you, burn in hell! Thank you!", claps: 0, queen_id: gigi_goode.id, user_added?: false)
Quote.create(quote: "Gay people judging me... BIG surprise.", claps: 1, queen_id: pearl.id, user_added?: false)
Quote.create(quote: "I've never even heard of Macbeth. Call me young, call me illiterate, whatever.", claps: 0, queen_id: pearl.id, user_added?: false)
Quote.create(quote: "I.. I hate it here!", claps: 0, queen_id: pearl.id, user_added?: false)
Quote.create(quote: "Someone told me for the first time in my life that I wear too much highlighter!", claps: 0, queen_id: farrah_moan.id, user_added?: false)
Quote.create(quote: "Let's get this roast a-cookin'!", claps: 1, queen_id: farrah_moan.id, user_added?: false)
Quote.create(quote: "Oh my God, I want her to play with matches.", claps: 1, queen_id: willam.id, user_added?: false)
Quote.create(quote: "I'm just trying to get a window seat on the way to hell.", claps: 0, queen_id: willam.id, user_added?: false)
Quote.create(quote: "I'm trying to bring attention to one of my favorite causes. Which is me.", claps: 0, queen_id: willam.id, user_added?: false)
Quote.create(quote: "You shut your ugly boat mouth!", claps: 0, queen_id: willam.id, user_added?: false)
Quote.create(quote: "I'm not gonna RuPaulogize for anything that I'm doing now.", claps: 0, queen_id: willam.id, user_added?: false)
Quote.create(quote: "You fucking cross-dressers made me cry.", claps: 0, queen_id: willam.id, user_added?: false)
Quote.create(quote: "DeLa for short, De for shorter, Ms. Creme if you're nasty!", claps: 0, queen_id: ben_de_la_creme.id, user_added?: false)
Quote.create(quote: "Don't fear the drag queen, fear the devil inside the drag queen.", claps: 1, queen_id: ben_de_la_creme.id, user_added?: false)
Quote.create(quote: "Barf.", claps: 0, queen_id: ben_de_la_creme.id, user_added?: false)
Quote.create(quote: "I'm just a plain old heteronormative girl.", claps: 1, queen_id: yvie_oddly.id, user_added?: false)
Quote.create(quote: "I'll dance circles around your ass.", claps: 0, queen_id: yvie_oddly.id, user_added?: false)
Quote.create(quote: "I DON'T NEED CORDIAL, BITCH. I NEED REAL!", claps: 0, queen_id: yvie_oddly.id, user_added?: false)
Quote.create(quote: "Follow your oddities and fly your freak flag!", claps: 0, queen_id: yvie_oddly.id, user_added?: false)
Quote.create(quote: "Odd Bless!", claps: 0, queen_id: yvie_oddly.id, user_added?: false)
Quote.create(quote: "Cha-ching, motherfucker, cha-ching.", claps: 0, queen_id: monet_x_change.id, user_added?: false)
Quote.create(quote: "Gag, bitch.", claps: 1, queen_id: monet_x_change.id, user_added?: false)
Quote.create(quote: "I'm perturbed, and disturbed. All the urbs.", claps: 0, queen_id: monet_x_change.id, user_added?: false)
Quote.create(quote: "You could be white Beyoncé, Weyoncé!", claps: 0, queen_id: monet_x_change.id, user_added?: false)
Quote.create(quote: "The Ultimate SHADE Of It All!", claps: 0, queen_id: latrice_royale.id, user_added?: false)
Quote.create(quote: "I want people to realize, that it's okay to make mistakes, it's okay to fall down. Get up, look sickening, and Make Them Eat It!", claps: 0, queen_id: latrice_royale.id, user_added?: false)
Quote.create(quote: "Y'all so white and Anglo Saxon and shit.", claps: 0, queen_id: latrice_royale.id, user_added?: false)
Quote.create(quote: "I may be fat bitch, but you're ugly and I can lose weight.", claps: 0, queen_id: latrice_royale.id, user_added?: false)
Quote.create(quote: "Showin' off muh curves 'n swerves.", claps: 0, queen_id: latrice_royale.id, user_added?: false)
Quote.create(quote: "Five G's please : Good God Get A Grip Girl.", claps: 1, queen_id: latrice_royale.id, user_added?: false)
Quote.create(quote: "She is large and in charge, chunky, yet funky. Bold and Beautiful baby.", claps: 0, queen_id: latrice_royale.id, user_added?: false)
Quote.create(quote: "Let me explain to you what a bitch is: Being In Total Control of Herself.", claps: 0, queen_id: latrice_royale.id, user_added?: false)
Quote.create(quote: "I feel that my presence is enough of a statement on its own, even in silence.", claps: 0, queen_id: raja.id, user_added?: false)
Quote.create(quote: "Watch out children, mother is here... okay, if Ru's mother, then I'm auntie. Auntie Raja is here and she's about to teach y'all a fucking lesson.", claps: 0, queen_id: raja.id, user_added?: false)
Quote.create(quote: "Institutions also spells intuitions! If you're dyslexic.", claps: 1, queen_id: raja.id, user_added?: false)
Quote.create(quote: "I have a master's degree in FIERCE.", claps: 0, queen_id: raja.id, user_added?: false)
Quote.create(quote: "Far too much sass, way too much ass.", claps: 0, queen_id: kameron_michaels.id, user_added?: false)
Quote.create(quote: "She looks fishy and she knows it.", claps: 0, queen_id: kameron_michaels.id, user_added?: false)
Quote.create(quote: "Cher and cockroaches!", claps: 1, queen_id: kameron_michaels.id, user_added?: false)
Quote.create(quote: "We're all just a bunch of clowns, aren't we?", claps: 1, queen_id: milk.id, user_added?: false)
Quote.create(quote: "If you say you're super smart, you're not. If you say your drag is art, it's not. If you say you didn't fart, you did.", claps: 0, queen_id: milk.id, user_added?: false)
Quote.create(quote: "I have the power of God and anime on my side.", claps: 1, queen_id: aja.id, user_added?: false)
Quote.create(quote: "Gooped and Gagged.", claps: 0, queen_id: aja.id, user_added?: false)
Quote.create(quote: "I'm an Illuminati princess, they tried to silence me and I'm like, no bitch I'm still gonna talk.", claps: 0, queen_id: aja.id, user_added?: false)
Quote.create(quote: "Girl, I feel like a soft serve ice cream cone right now!", claps: 0, queen_id: aja.id, user_added?: false)
Quote.create(quote: "I don't wanna say I read her, I just aggressively complimented her.", claps: 0, queen_id: aja.id, user_added?: false)
Quote.create(quote: "Today I see myself as a strong bitch.", claps: 0, queen_id: blair_st_clair.id, user_added?: false)
Quote.create(quote: "I do declare...", claps: 0, queen_id: blair_st_clair.id, user_added?: false)
Quote.create(quote: "It was terrible! We were in there and there was...overhead lighting!", claps: 0, queen_id: blair_st_clair.id, user_added?: false)
Quote.create(quote: "No one calls me dumb, you lint-licker!", claps: 0, queen_id: blair_st_clair.id, user_added?: false)
Quote.create(quote: "That's what your man said last night.", claps: 1, queen_id: blair_st_clair.id, user_added?: false)
Quote.create(quote: "She's Venus with a penis.", claps: 0, queen_id: scarlet_envy.id, user_added?: false)
Quote.create(quote: "When you feel your own oats so hard, you forget that there are other oats there.", claps: 0, queen_id: scarlet_envy.id, user_added?: false)
Quote.create(quote: "Is it me? Am I the drama? I don't think I'm the drama... Maybe I am...", claps: 1, queen_id: scarlet_envy.id, user_added?: false)
Quote.create(quote: "Mother earth is climate changing so we better change too.", claps: 0, queen_id: scarlet_envy.id, user_added?: false)
Quote.create(quote: "Shady. Boots. Shady boots.", claps: 1, queen_id: jaida_essence_hall.id, user_added?: false)
Quote.create(quote: "Keep your ass right, and your mind will follow.", claps: 0, queen_id: jaida_essence_hall.id, user_added?: false)
Quote.create(quote: "Ooh, y'all are not feeling me.", claps: 0, queen_id: jaida_essence_hall.id, user_added?: false)
Quote.create(quote: "Sometimes it pays to be delusional.", claps: 0, queen_id: jaida_essence_hall.id, user_added?: false)
Quote.create(quote: "This is not RuPaul's Excuse Race!", claps: 0, queen_id: jaida_essence_hall.id, user_added?: false)
Quote.create(quote: "Oh, werk bitch.", claps: 1, queen_id: thorgy_thor.id, user_added?: false)
Quote.create(quote: "That was a messy mess." , claps: 0, queen_id: thorgy_thor.id, user_added?: false)
Quote.create(quote: "Okay, I am obsessed with mustard. I can't believe I just said that out loud!", claps: 0, queen_id: thorgy_thor.id, user_added?: false)
Quote.create(quote: "Oh, hi! I'm just eating fruit snacks.", claps: 0, queen_id: thorgy_thor.id, user_added?: false)
Quote.create(quote: "I can feel the wind go up my ass, which is amazing, I haven't felt that in weeks.", claps: 0, queen_id: nina_west.id, user_added?: false)
Quote.create(quote: "It is our responsibility to create the world that we wanna live in.", claps: 1, queen_id: nina_west.id, user_added?: false)
Quote.create(quote: "You know you really shouldn't play the victim. It doesn't suit you, you don't do it well.", claps: 0, queen_id: tatianna.id, user_added?: false)
Quote.create(quote: "I am not done talking yet. You will speak when I'm done.", claps: 0, queen_id: tatianna.id, user_added?: false)
Quote.create(quote: "We all make choices, but that was a CHOICE.", claps: 1, queen_id: tatianna.id, user_added?: false)
Quote.create(quote: "Stupid bitch", claps: 0, queen_id: tatianna.id, user_added?: false)
Quote.create(quote: "She is gonna gag you, honey. She is- I'm a production!", claps: 0, queen_id: monique_heart.id, user_added?: false)
Quote.create(quote: "I can't, I'm queening out right now!", claps: 1, queen_id: monique_heart.id, user_added?: false)
Quote.create(quote: "America, my face is saying everything you need to know.com", claps: 0, queen_id: monique_heart.id, user_added?: false)
Quote.create(quote: "Oh, you decadent chocolate bar you! Succulent!", claps: 0, queen_id: monique_heart.id, user_added?: false)
Quote.create(quote: "I came to this competition with glitter and Jesus! And bitch, I'm making it work, okay!?", claps: 0, queen_id: monique_heart.id, user_added?: false)
Quote.create(quote: "Point Blank Period.", claps: 0, queen_id: monique_heart.id, user_added?: false)
Quote.create(quote: "That is fake as fuck dot com!", claps: 0, queen_id: monique_heart.id, user_added?: false)
Quote.create(quote: "Just like Jesus rose Lazarus, for some reason, He rose these horrible hoes. No.", claps: 0, queen_id: monique_heart.id, user_added?: false)
Quote.create(quote: "What is done in the dark shall be brought to the light, mother darling, the light's on.", claps: 0, queen_id: monique_heart.id, user_added?: false)
Quote.create(quote: "America, it's time to stop hiding in the closet! (high-pitched tongue trill)", claps: 0, queen_id: heidi_n_closet.id, user_added?: false)
Quote.create(quote: "Leprosy print.", claps: 0, queen_id: heidi_n_closet.id, user_added?: false)
Quote.create(quote: "Blessed and highly favored.", claps: 0, queen_id: heidi_n_closet.id, user_added?: false)
Quote.create(quote: "Overall she delivered…literally 'cause she was pregnant.", claps: 0, queen_id: heidi_n_closet.id, user_added?: false)
Quote.create(quote: "Hairspray and desperation.", claps: 0, queen_id: heidi_n_closet.id, user_added?: false)
Quote.create(quote: "I love Lunchables, honey!", claps: 1, queen_id: heidi_n_closet.id, user_added?: false)
Quote.create(quote: "Y'all gonna have to call me the umpire, cause bitch, I'm about to call these bitches out.", claps: 0, queen_id: heidi_n_closet.id, user_added?: false)
Quote.create(quote: "Creole fish!", claps: 0, queen_id: chi_chi_devayne.id, user_added?: false)
Quote.create(quote: "If you ain't stepping that pussy up, your ass is going home.", claps: 0, queen_id: chi_chi_devayne.id, user_added?: false)
Quote.create(quote: "Creole fish!", claps: 0, queen_id: chi_chi_devayne.id, user_added?: false)
Quote.create(quote: "This is some bullllshit.", claps: 1, queen_id: chi_chi_devayne.id, user_added?: false)
Quote.create(quote: "YES. BITCH. WERK!", claps: 0, queen_id: gia_gunn.id, user_added?: false)
Quote.create(quote: "Gag me with a Delorean!", claps: 0, queen_id: gia_gunn.id, user_added?: false)
Quote.create(quote: "Oh sweetie, I'm very secure, are you secure?", claps: 0, queen_id: gia_gunn.id, user_added?: false)
Quote.create(quote: "I'm feeling my oats, let me feel my ooooooooats!", claps: 1, queen_id: gia_gunn.id, user_added?: false)
Quote.create(quote: "OKUURRRRRRR!!!", claps: 1, queen_id: laganja_estranja.id, user_added?: false)
Quote.create(quote: "Yas Gawd!", claps: 0, queen_id: laganja_estranja.id, user_added?: false)
Quote.create(quote: "I FEEL VERY ATTACKED!", claps: 0, queen_id: laganja_estranja.id, user_added?: false)
Quote.create(quote: "Because if it ain't green, HUH, I'm not interested, OKAAAAAY?!", claps: 0, queen_id: laganja_estranja.id, user_added?: false)
Quote.create(quote: "Well I'm young and I'm hung and I clearly march to the sound of my own drum, so props to ya, mawma!", claps: 0, queen_id: laganja_estranja.id, user_added?: false)

puts "✅ Done seeding!"
